SELECT DISTINCT C.SALESPERSONNO,COUNT(C.SALESPERSONNO)"NUMBER OF CARS SOLD"
FROM CARSALE C,SALESPERSON S
WHERE C.SALESPERSONNO=S.SALESPERSONNO
AND C.SALEDATE BETWEEN '01-MAY-24' AND '31-OCT-24'
GROUP BY C.SALESPERSONNO
HAVING COUNT (C.SALESPERSONNO)>0
ORDER BY C.SALESPERSONNO;

-- SINCE SQL DOES NOT DISPLAY COUNT=0, WE SHOULD ALSO CHECK IF THERE IS A SELLER WHO HAS NOT SOLD ANY CAR IN THE PAST 6 MONTHS:
SELECT DISTINCT SALESPERSONNO
FROM CARSALE C
WHERE NOT EXISTS (SELECT CARSALENO
FROM CARSALE CR
WHERE C.SALESPERSONNO=CR.SALESPERSONNO AND CR.SALEDATE>'01-MAY-24');
