SELECT DISTINCT SALESPERSONNO,SUM(PRICE) "TOTAL COST OF THE CARS"
FROM CARSALE
WHERE SALEDATE LIKE'%%-OCT-24'
GROUP BY SALESPERSONNO;


-- TO CHECK IF THERE IS A SELLER WHO HAS NOT SOLD ANY CAR IN THE PAST MONTH:
SELECT DISTINCT SALESPERSONNO
FROM CARSALE C
WHERE NOT EXISTS (SELECT CARSALENO
    FROM CARSALE CR
    WHERE C.SALESPERSONNO=CR.SALESPERSONNO 
    AND CR.SALEDATE LIKE'%%-OCT-24');
