SELECT SALESPERSONNO,SUM(COMMISSION/100*PRICE) "EARNED COMMISSION"
FROM CARSALE 
WHERE SALEDATE LIKE'%%-OCT-24'
GROUP BY SALESPERSONNO;



--SECOND OPTION
--WE CAN CREATE A NEW COMMISSION TABLE THAT CONTAINS COMMISSION PERCENTAGE AND CORRESPONDING BOUNDS:

CREATE TABLE COMMISSION
(COMMPERCENT    NUMBER,
LPRICE          NUMBER,
HPRICE          NUMBER);

INSERT INTO COMMISSION VALUES (0.02,0,5000);
INSERT INTO COMMISSION VALUES (0.03,5001,10000);
INSERT INTO COMMISSION VALUES (0.04,10001,15000);
INSERT INTO COMMISSION VALUES (0.05,15001,50000);

--THEN WE CAN USE THE FOLLOWING STATEMENT DO DISPLAY THE RELEVANT DATA:
SELECT DISTINCT C.SALESPERSONNO,SUM(COMMPERCENT*PRICE) COMM
FROM CARSALE C, COMMISSION CM
WHERE SALEDATE LIKE'%%-OCT-24'
AND C.PRICE BETWEEN LPRICE AND HPRICE
GROUP BY C.SALESPERSONNO;

