SELECT DISTINCT CR.CARINFO,CR.REGNO,S.SALESPERSONNO,S.NAME SELLER,C.CUSTOMERNO,C.NAME CUSTOMER,C.ADDRESS "CUSTOMER ADDRESS"
FROM CARSALE CR,SALESPERSON S,CUSTOMER C
WHERE SALEDATE LIKE'%%-OCT-24'
AND S.SALESPERSONNO=CR.SALESPERSONNO
AND C.CUSTOMERNO=CR.CUSTOMERNO
ORDER BY SALESPERSONNO;