CREATE TABLE CENTRE
(CENTRENO CHAR(4) NOT NULL,
ADDRESS CHAR(50),
CONTACTNUMBER CHAR(14),
CONSTRAINT Centre_CentreNo_Pk PRIMARY KEY(CENTRENO));


CREATE TABLE SALESPERSON
(SALESPERSONNO CHAR(10) NOT NULL,
NAME CHAR(30) NOT NULL,
CENTRENO CHAR(4) NOT NULL,
CONSTRAINT Salesperson_SalespersonNo_Pk PRIMARY KEY(SALESPERSONNO ),
CONSTRAINT Salesperson_CentreNo_Fk FOREIGN KEY(CENTRENO) REFERENCES
CENTRE(CENTRENO));


CREATE TABLE CUSTOMER
(CUSTOMERNO CHAR(4) NOT NULL,
NAME CHAR(30) NOT NULL,
ADDRESS CHAR(50),
TELEPHONENO CHAR(14),
CONSTRAINT Customer_CustomerNo_Pk PRIMARY KEY(CUSTOMERNO));


CREATE TABLE CARSALE
(CARSALENO CHAR(4) NOT NULL,
SALESPERSONNO CHAR(10),
CUSTOMERNO CHAR(4) NOT NULL,
SALEDATE DATE,
CARINFO CHAR(50),
REGNO CHAR(10),
PRICE NUMBER(10),
COMMISSION NUMBER(4),
CONSTRAINT CarSale_Pk PRIMARY KEY(CARSALENO),
CONSTRAINT CarSale_SalespersonNo_Fk FOREIGN KEY(SALESPERSONNO) REFERENCES
SALESPERSON(SALESPERSONNO),
CONSTRAINT CarSale_CustomerNo_Fk FOREIGN KEY(CUSTOMERNO) REFERENCES
CUSTOMER(CUSTOMERNO));
